function Dashboard({state,books,go,newDoc,range,setRange,user,setup}){
 const [mode,setMode]=useState('overview'),[gran,setGran]=useState('month'),[tx,setTx]=useState('all'),[settlement,setSettlement]=useState('collect');
 const C=useC(),from=range.from,to=range.to;
 const P=useMemo(()=>pnl(books.flat,from,to),[books,from,to]);
 const pastEnd=addDays(from,-1),pastStart=addDays(from,-rangeDays(range));
 const prior=useMemo(()=>pnl(books.flat,pastStart,pastEnd),[books,pastStart,pastEnd]);
 const periodBooks=useMemo(()=>deriveBooks({...state,docs:state.docs.filter(d=>d.date<=to),payments:state.payments.filter(d=>d.date<=to),manual:state.manual.filter(d=>d.date<=to),stockOps:state.stockOps.filter(d=>d.date<=to)}),[state,to]);
 const ar=useMemo(()=>aging(state,'receivable',to),[state,to]),ap=useMemo(()=>aging(state,'payable',to),[state,to]);
 const buckets=useMemo(()=>bucketize(from,to,gran),[from,to,gran]);
 const bankCodes=ACCOUNTS.filter(a=>a.type==='bank').map(a=>a.code);
 const cashAt=date=>R2(books.flat.filter(l=>bankCodes.includes(l.acc)&&l.date<=date).reduce((s,l)=>s+l.debit-l.credit,0));
 const series=buckets.rows.map(b=>{const p=pnl(books.flat,b.from,b.to);return {label:b.label,full:b.full,revenue:p.revenue,cost:p.cost+p.expense,profit:p.net,cash:cashAt(b.to)};});
 const cash=cashAt(to),inventory=Object.values(periodBooks.stock).reduce((s,x)=>s+x.value,0);
 const dueBook=settlement==='collect'?ar:ap;
 const openItems=dueBook.rows.flatMap(r=>r.items.map(i=>({...i,partner:r.partner,days:daysBetween(i.due,to)}))).sort((a,b)=>b.days-a.days||b.open-a.open);
 const openTotal=R2(openItems.reduce((sum,i)=>sum+i.open,0)),overdueTotal=R2(openItems.filter(i=>i.days>0).reduce((sum,i)=>sum+i.open,0));
 const unapplied=R2(dueBook.rows.reduce((sum,r)=>sum+r.unapplied,0)),drafts=state.docs.filter(x=>x.state==='draft');
 const movement=cashMovement(books.entries,bankCodes,from,to);
 const flowSeries=bucketize(from,to,rangeDays(range)>90?'month':rangeDays(range)>31?'week':'day').rows.map(b=>({...b,...cashMovement(books.entries,bankCodes,b.from,b.to)}));
 const flowMax=Math.max(1,...flowSeries.flatMap(b=>[b.incoming,b.outgoing]));
 const topProducts=useMemo(()=>{
   const rows={};state.docs.filter(d=>['invoice','credit_note'].includes(d.type)&&d.state==='posted'&&inRange(d.date,from,to)).forEach(d=>{
     const sign=d.type==='invoice'?1:-1;amounts(d).lines.forEach(l=>{if(!PROD[l.product])return;const r=rows[l.product]||(rows[l.product]={id:l.product,qty:0,value:0});r.qty+=sign*+l.qty;r.value+=sign*l.amount;});
   });return Object.values(rows).filter(r=>r.value>0).sort((a,b)=>b.value-a.value).slice(0,4);
 },[state,from,to]);
 const low=PRODUCTS.filter(p=>p.kind==='goods'&&(books.stock[p.id]?.qty||0)<=(p.reorder??5));

 const top=useMemo(()=>{const m={};state.docs.filter(d=>['invoice','credit_note'].includes(d.type)&&d.state==='posted'&&inRange(d.date,from,to)).forEach(d=>{m[d.partner]=(m[d.partner]||0)+amounts(d).net*(d.type==='invoice'?1:-1);});return Object.entries(m).map(([id,v])=>({id,name:PMAP[id]?.name||id,value:R2(v)})).filter(x=>x.value>0).sort((a,b)=>b.value-a.value).slice(0,5);},[state,from,to]);
 const recent=state.docs.filter(d=>inRange(d.date,from,to)&&(tx==='all'||DOCMETA[d.type].side===tx)).slice().sort((a,b)=>b.date.localeCompare(a.date)||b.number.localeCompare(a.number)).slice(0,6);
 const firstDate=books.flat.reduce((m,l)=>l.date<m?l.date:m,'9999-12-31');
 const delta=(v,p)=>p&&pastStart>=firstDate?((v-p)/Math.abs(p)*100):null;
 const stats=[{label:'Total revenue',value:P.revenue,icon:TrendingUp,tone:'mint',delta:delta(P.revenue,prior.revenue),values:series.map(x=>x.revenue),go:'r_pnl',sub:'Net of credit notes'},
 {label:'Total costs',value:P.cost+P.expense,icon:Wallet,tone:'peach',delta:delta(P.cost+P.expense,prior.cost+prior.expense),values:series.map(x=>x.cost),go:'r_pnl',sub:'Cost of sales + expenses'},
 {label:'Net profit',value:P.net,icon:BarChart3,tone:'lilac',delta:delta(P.net,prior.net),values:series.map(x=>x.profit),go:'r_pnl',sub:P.nm.toFixed(1)+'% net margin'},
 {label:'Inventory value',value:inventory,icon:Package,tone:'blue',delta:null,values:[],go:'r_stock',sub:'As at '+dmy(to)}];
 return <div className="studio-dashboard"><div className="dashboard-head"><div><div className="eyebrow"><span/>YOUR BUSINESS AT A GLANCE</div><h1>Business overview<span>.</span></h1><p>{greeting()}, {user.name.split(' ')[0]}. Here’s where things stand.</p></div><div className="acts"><div className="seg period-shortcuts" aria-label="Dashboard period">{[['mtd','Month'],['qtd','Quarter'],['ytd','Year'],['d365','12 months']].map(([key,label])=><button key={key} className={range.preset===key?'on':''} onClick={()=>{const [from,to]=PRESETS.find(p=>p[0]===key)[2]();setRange({preset:key,from,to});}}>{label}</button>)}</div><RangePicker value={range} onChange={setRange}/><Btn icon={BarChart3} onClick={()=>go('r_pnl')}>Reports</Btn></div></div>
 <div className="dashboard-view-tabs"><div className="seg"><button className={mode==='overview'?'on':''} onClick={()=>{setMode('overview');scrollPageTop();}} >Overview</button><button className={mode==='detail'?'on':''} onClick={()=>{setMode('detail');scrollPageTop();}} >Financial detail</button></div><span><i className="live-dot"/> {books.balanced?'Ledger balanced':'Ledger needs review'} · {dmy(to)}</span></div>
 {setup}
 {mode==='detail'?<LegacyDashboard state={state} books={books} go={go} newDoc={newDoc} range={range} setRange={setRange} user={user}/>:<>
 <div className="dashboard-hero-row"><section className="cash-hero"><div className="cash-top"><span className="cash-icon"><Landmark size={20}/></span><span>Cash & bank balance</span><span className="hero-currency">AED</span></div><div className="cash-value">{money(cash,false)}</div><p>Across {bankCodes.length} cash and bank accounts · as at {dmy(to)}</p><div className="cash-foot"><button onClick={()=>go('banking')}>Open banking <ArrowUpRight size={16}/></button><span>Posted transactions</span></div><div className="cash-art"><div className="cash-orbit o1"/><div className="cash-orbit o2"/><div className="cash-orbit o3"/><div className="cash-bars">{series.slice(-12).map((m,i)=><i key={i} style={{height:(12+Math.abs(m.cash)/Math.max(1,...series.map(x=>Math.abs(x.cash)))*85)+'%'}}/>)}</div></div></section>
 <section className="quick-actions"><div className="section-title"><div><span className="micro">QUICK ACTIONS</span><h2>Move your business forward</h2></div><Zap size={20}/></div><div className="quick-grid">{[[FileText,'New invoice','Get paid for your work',()=>newDoc('invoice'),'mint'],[ShoppingCart,'New bill','Record a purchase',()=>newDoc('bill'),'blue'],[Layers,'Stock count','Keep quantities accurate',()=>go('stock_count'),'lilac'],[Users,'Customers','Manage relationships',()=>go('partners'),'peach']].map(([Icon,label,sub,act,tone])=><button key={label} onClick={act}><span className={'quick-icon '+tone}><Icon size={21}/></span><span><b>{label}</b><small>{sub}</small></span><ArrowUpRight size={16}/></button>)}</div></section></div>
 <div className="studio-kpis">{stats.map((s,i)=><button className={'studio-kpi '+s.tone} key={s.label} onClick={()=>go(s.go)}><div className="kpi-label"><span>{s.label}</span><s.icon size={18}/></div><div className="kpi-value"><small>AED</small>{money(s.value,false)}</div><div className="kpi-foot"><span>{s.sub}</span>{s.delta!==null&&<b className="delta-badge" title={`Compared with ${dmy(pastStart)} to ${dmy(pastEnd)}`}>{s.delta>=0?'+':''}{s.delta.toFixed(1)}%</b>}</div><div className="kpi-trend">{s.values.length>1?<Sparkline data={s.values} color={i===0?C.pos:i===1?C.c2:C.c3} w={168} h={28}/>:<span><Boxes size={15}/>{low.length} items currently low</span>}</div><div className="kpi-bottom-line"/></button>)}</div>
 <div className="dashboard-chart-row"><Card className="revenue-card" title="Revenue & costs" sub={`${dmy(from)} — ${dmy(to)} · AED`} right={<div className="seg">{[['day','Day'],['week','Week'],['month','Month']].map(([v,l])=><button key={v} className={gran===v?'on':''} onClick={()=>setGran(v)}>{l}</button>)}</div>}><div className="chart-legend"><span><i style={{background:'#168775'}}/>Revenue</span><span><i style={{background:'#a2afc5'}}/>Total costs</span></div><AreaChart data={series} height={244} labelEvery={Math.max(1,Math.ceil(series.length/9))} series={[{key:'revenue',name:'Revenue',color:'#168775',fill:0.16},{key:'cost',name:'Total costs',color:'#a2afc5',fill:0.04}]}/><div className="chart-bottom"><span>Gross profit <b>AED {money(P.gross,false)}</b></span><span>Gross margin <b>{P.gm.toFixed(1)}%</b></span><button onClick={()=>go('r_pnl')}>Explore report <ArrowUpRight size={14}/></button></div></Card>
 <Card className="receivables-card" title={settlement==='collect'?'Money to collect':'Money to pay'} sub={`Open ${settlement==='collect'?'invoices':'bills'} as at ${dmy(to)}`} right={<div className="seg settlement-switch" aria-label="Settlement view"><button className={settlement==='collect'?'on':''} onClick={()=>setSettlement('collect')}>Collect</button><button className={settlement==='pay'?'on':''} onClick={()=>setSettlement('pay')}>Pay</button></div>}><div className="collection-total"><small>AED</small><b>{money(openTotal,false)}</b><span>{openItems.length} open</span></div><div className="collection-bar"><i style={{width:(openTotal?overdueTotal/openTotal*100:0)+'%'}}/></div><div className="collection-label"><span><i/>Overdue <b>{money(overdueTotal,false)}</b></span><span>Not due <b>{money(openTotal-overdueTotal,false)}</b></span></div><div className="collection-list">{openItems.slice(0,3).map(i=><button key={i.id} onClick={()=>go(settlement==='collect'?'invoices':'bills',i.id)}><Avatar name={i.partner.name} size={32}/><span><b>{i.partner.name}</b><small>{i.days>0?i.days+' days overdue':i.days===0?'Due today':'Due in '+(-i.days)+' days'} · {i.number}</small></span><strong>{money(i.open,false)}</strong></button>)}{!openItems.length&&<div className="collection-clear"><CircleCheck size={26}/><b>All caught up</b><span>No open {settlement==='collect'?'invoices':'bills'} on this date.</span></div>}</div>{unapplied>0&&<p className="collection-credit">Unapplied credits: AED {money(unapplied,false)} · Net balance {money(dueBook.grand,false)}</p>}<Btn onClick={()=>go(settlement==='collect'?'r_aged_ar':'r_aged_ap')}>Manage {settlement==='collect'?'receivables':'payables'} <ArrowRight size={14}/></Btn></Card></div>
 <div className="dashboard-attention"><div><span className="quick-icon peach"><Bell size={19}/></span><span><b>Keep things moving</b><small>Your next priorities</small></span></div><button onClick={()=>drafts[0]?go(LIST_OF[drafts[0].type],drafts[0].id):go('invoices')}><b>{drafts.length}</b><span>Draft documents</span><ArrowUpRight size={14}/></button><button onClick={()=>go('products','__low_stock__')}><b>{low.length}</b><span>Low stock items</span><ArrowUpRight size={14}/></button><button onClick={()=>go('r_aged_ap')}><b>{money(ap.grand,false)}</b><span>Payable · AED</span><ArrowUpRight size={14}/></button></div>
 <div className="dashboard-lower-row"><Card title="Recent transactions" sub="Latest activity in the selected period" pad={false} right={<div className="seg">{[['all','All'],['sale','Sales'],['purchase','Purchases']].map(([v,l])=><button key={v} className={tx===v?'on':''} onClick={()=>setTx(v)}>{l}</button>)}</div>}><div className="tbl-wrap"><table className="tbl recent-table"><thead><tr><th>Document / partner</th><th>Date</th><th className="n">Total · AED</th><th>Status</th><th/></tr></thead><tbody>{recent.map(d=><tr key={d.id}><td><button className="transaction-name" onClick={()=>go(LIST_OF[d.type],d.id)}><span className={cx('transaction-icon',DOCMETA[d.type].side==='sale'?'mint':'blue')}><FileText size={17}/></span><span><b>{d.number}</b><small>{PMAP[d.partner]?.name}</small></span></button></td><td>{dmy(d.date)}</td><td className="n"><b>{money(amounts(d).total,false)}</b></td><td><Pill tone={d.state==='posted'?'ok':''} dot>{d.state}</Pill></td><td><button className="icon-btn" title={'Open '+d.number} onClick={()=>go(LIST_OF[d.type],d.id)}><ArrowUpRight size={15}/></button></td></tr>)}{!recent.length&&<tr><td colSpan="5"><EmptyState title="No transactions in this period">Choose a wider date range.</EmptyState></td></tr>}</tbody></table></div></Card>
 <Card title="Top customers" sub="Ranked by net revenue" right={<button className="icon-btn" title="Customer profitability" onClick={()=>go('r_cust')}><ArrowUpRight size={18}/></button>}><div className="studio-ranking">{top.map((r,i)=><button key={r.id} onClick={()=>go('r_partner',r.id)}><span className="rank-number">0{i+1}</span><span><b>{r.name}</b><i className="rank-track"><i style={{width:(r.value/(top[0]?.value||1)*100)+'%'}}/></i></span><strong>{money(r.value,false)}</strong></button>)}{!top.length&&<EmptyState icon={Users} title="No sales yet"/>}</div></Card></div>
 <div className="dashboard-insights-row"><Card title="Cash movement" sub="Posted cash and bank activity in the selected period" right={<button className="icon-btn" title="Open banking" onClick={()=>go('banking')}><ArrowUpRight size={18}/></button>}><div className="flow-totals"><div><span><i className="flow-in"/>Money in</span><b>{money(movement.incoming,false)}</b></div><div><span><i className="flow-out"/>Money out</span><b>{money(movement.outgoing,false)}</b></div><div><span>Net movement · AED</span><b className={movement.net<0?'neg':'pos'}>{movement.net>0?'+':''}{money(movement.net,false)}</b></div></div><div className="flow-chart" role="img" aria-label={`Cash movement: incoming AED ${movement.incoming}, outgoing AED ${movement.outgoing}.`} style={{gridTemplateColumns:`repeat(${flowSeries.length},minmax(8px,1fr))`}}>{flowSeries.map((b,i)=><div className="flow-period" key={i} title={`${b.full}: in ${money(b.incoming,false)}, out ${money(b.outgoing,false)}`}><div><i className="flow-in" style={{height:(b.incoming/flowMax*100)+'%'}}/><i className="flow-out" style={{height:(b.outgoing/flowMax*100)+'%'}}/></div><span>{i%Math.max(1,Math.ceil(flowSeries.length/9))===0?b.label:''}</span></div>)}</div><div className="flow-note"><span>Includes all posted cash movements.</span><span>Transfers between cash / bank accounts excluded.</span></div></Card><Card title="Best-selling products" sub="Net sales after returns · excluding VAT" right={<button className="icon-btn" title="Product profitability" onClick={()=>go('r_prod')}><ArrowUpRight size={18}/></button>}><div className="product-ranking">{topProducts.map((r,i)=>{const p=PROD[r.id];return <button key={r.id} onClick={()=>go('products',r.id)}><span className={'quick-icon '+['mint','blue','lilac','peach'][i]}><Package size={21}/></span><span><b>{p.name}</b><small>{p.code} · {R2(r.qty)} {p.uom.toLowerCase()} net</small></span><strong>{money(r.value,false)}<small>AED</small></strong></button>;})}{!topProducts.length&&<EmptyState icon={Package} title="Your best sellers will appear here">Post an invoice to begin tracking product performance.</EmptyState>}</div></Card></div>
 <div className="dashboard-footer"><span><Scale size={14}/> Every figure is connected to your books.</span><span>Period comparison: {dmy(pastStart)} — {dmy(pastEnd)} · Currency AED</span></div>
 </>}
 </div>;
}
